version: 2

builds:
  - binary: review-for-agent
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

release:
  github:
    owner: Waraq-Labs
    name: review-for-agent
