version: 2

builds:
  - binary: review-for-agent
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64

signs:
  - cmd: gon
    args:
      - gon.hcl
    artifacts: darwin

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  disable: true

changelog:
  disable: true

release:
  github:
    owner: Waraq-Labs
    name: review-for-agent
  mode: append
